[package]
name = "rmd"
version = "0.1.19"
edition = "2021"
license = "MIT"
description = "A fast cross-platform file/directory removal tool, written in Rust (rimraf alternative)"
repository = "https://github.com/yanxxit/rmd"
homepage = "https://github.com/yanxxit/rmd"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", default-features = false, features = ["napi6"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = true
opt-level = 3
codegen-units = 1
