/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * 同步删除一个或多个路径（文件、目录或符号链接）。
 * 路径不存在时视为成功（幂等）。
 */
export declare function removeSync(targets: Array<string>): void
/** 异步删除一个或多个路径（在 libuv 线程池中执行）。 */
export declare function removeAsync(targets: Array<string>): Promise<unknown>
/** 判断路径是否存在（不跟随符号链接）。 */
export declare function pathExists(target: string): boolean
