import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
// native.cjs is auto-generated by napi-rs (CommonJS). With "type": "module"
// we load it through createRequire so the require()-based shim works.
const native = require("./native.cjs");

// napi bindings accept an array of paths (Vec<String>); normalize a single
// string (or any non-array) into an array so `removeSync("dist")` and
// `removeSync(["a","b"])` both work.
function toTargets(targets) {
  if (Array.isArray(targets)) return targets;
  if (targets == null) return [];
  return [targets];
}

// Re-export the napi-generated bindings for the public API.
export function removeSync(targets) {
  return native.removeSync(toTargets(targets));
}

export function removeAsync(targets) {
  return native.removeAsync(toTargets(targets));
}

export const pathExists = native.pathExists;
