/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

export function removeSync(targets: Array<string>, progress?: (done: number, total: number) => void, countTotal?: boolean): void
export function removeAsync(targets: Array<string>, progress?: (done: number, total: number) => void, countTotal?: boolean): Promise<void>
export function pathExists(target: string): boolean
