/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

export function removeSync(targets: Array<string>): void
export function removeAsync(targets: Array<string>): Promise<void>
export function pathExists(target: string): boolean
